export const MACHINE_INSTANCE_STATUS_TYPE_CONFIGURATIONS = {
  PENDING: {
    code: 'PENDING',
    icon: 'sym_o_model_training',
    textColor: 'grey',
    bgColor: 'grey-1',
    originColor: 'grey',
  },
  COMPLETED: {
    code: 'COMPLETED',
    icon: 'sym_o_rocket_launch',
    textColor: 'positive',
    bgColor: 'green-1',
    originColor: 'green',
  },
  ERROR: {
    code: 'ERROR',
    icon: 'sym_o_warning',
    textColor: 'negative',
    bgColor: 'red-1',
    originColor: 'red',
  },
  SUSPENDED: {
    code: 'SUSPENDED',
    icon: 'sym_o_autostop',
    textColor: 'blue',
    bgColor: 'blue-1',
    originColor: 'blue',
  },
}
export const MACHINE_INSTANCE_STATUS_CONFIGURATIONS = {
  FAILED_TO_CLEAR: {
    code: 'FAILED_TO_CLEAR',
    name: 'Failed to clear',
    icon: 'sym_o_autostop',
    textColor: 'negative',
    bgColor: 'red-1',
    originColor: 'red',
  },
  FAILURE: {
    code: 'FAILURE',
    name: 'Failure',
    icon: 'sym_o_autostop',
    textColor: 'negative',
    bgColor: 'red-1',
    originColor: 'red',
  },
  STARTING: {
    code: 'STARTING',
    name: 'Starting',
    icon: 'sym_o_autostop',
    textColor: 'grey',
    bgColor: 'grey-1',
    originColor: 'grey',
  },
  RUNNING: {
    code: 'RUNNING',
    name: 'Running',
    icon: 'sym_o_autostop',
    textColor: 'positive',
    bgColor: 'green-1',
    originColor: 'green',
  },
  SHUTDOWN: {
    code: 'SHUTDOWN',
    name: 'Shutdown',
    icon: 'sym_o_autostop',
    textColor: 'negative',
    bgColor: 'red-1',
    originColor: 'red',
  },
  WAITING_IN_QUEUE: {
    code: 'WAITING_IN_QUEUE',
    name: 'Waiting in queue',
    icon: 'sym_o_autostop',
    textColor: 'grey',
    bgColor: 'grey-1',
    originColor: 'grey',
  },
  CANCEL: {
    code: 'CANCEL',
    name: 'Cancel',
    icon: 'sym_o_autostop',
    textColor: 'negative',
    bgColor: 'red-1',
    originColor: 'red',
  },
  SHUTTING_DOWN: {
    code: 'SHUTTING_DOWN',
    name: 'Shutting down',
    icon: 'sym_o_autostop',
    textColor: 'negative',
    bgColor: 'red-1',
    originColor: 'red',
  },
  PAUSING: {
    code: 'PAUSING',
    name: 'Pausing',
    icon: 'sym_o_autostop',
    textColor: 'warning',
    bgColor: 'yellow-1',
    originColor: 'yellow',
  },
  PAUSED: {
    code: 'PAUSED',
    name: 'Paused',
    icon: 'sym_o_autostop',
    textColor: 'warning',
    bgColor: 'yellow-1',
    originColor: 'yellow',
  },
  RESUMING: {
    code: 'RESUMING',
    name: 'Resuming',
    icon: 'sym_o_autostop',
    textColor: 'positive',
    bgColor: 'green-1',
    originColor: 'green',
  },
  HAND_SHUTTING_DOWN: {
    code: 'HAND_SHUTTING_DOWN',
    name: 'Hand shutting down',
    icon: 'sym_o_autostop',
    textColor: 'negative',
    bgColor: 'red-1',
    originColor: 'red',
  },
}
